### ISSUE TITLE
Roadmap for Components

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-vue-components#29]
Some ideas for plans in the next version with the aim to use the components in the following projects, supported by openEO Platform:
- openEO Web Editor
- openEO Jupyter Widgets
- openEO Python Client
- openEO R Client
- (openEO Hub)

Inherit from 1.0: Description, LinkList, Tab, Tabs, ...

Ideas:
- Don't migrate automatically by default?
- Make general-purpose component for lists (like for tabs), which also includes search functionality.
- Release as [Async Web Components](https://cli.vuejs.org/guide/build-targets.html#async-web-component) #28 

**v2.0**:
- [x] Capabilities
  - [x] SupportedFeatures
  - [x] Billing Plans
- [x] FileFormats
  - [x] FileFormat
- [x] ServiceTypes
  - [x] ServiceType
- [x] UdfRuntimes
  - [x] UdfRuntime
- [x] STAC
  - [x] Collections
  - [x] Collection
  - [x] Item
- [x] Processes
  - [x] Process
- [x] Batch Job
  - [x] Overview / Table
  - [x] Results / Item (STAC)
- [x] Service Overview / Table
- [x] Files Overview / Table

**v2.1** (SRR2):
- [x] Logs
- [x] Batch Job Details
- [x] Batch Job Estimate
- [x] Service Details
- [x] User-Defined Process Overview / Table (-> use `Processes` instead)

**v2.3** (SRR3/4):
- [ ] User Account Details
- [ ] Model Builder
- [ ] Supported Versions (via capabilities?)

**Comment by m-mohr** [comment]
The model builder has a separate issue now: #47 

All other components are either implemented or don't have a use case right now, so closing here.
